SELECT A.FOOD_TYPE, REST_ID, REST_NAME, A.FAVORITES
FROM(
SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE) A JOIN REST_INFO R
ON A.FOOD_TYPE = R.FOOD_TYPE
WHERE A.FAVORITES = R.FAVORITES
ORDER BY FOOD_TYPE DESC


# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES)
# FROM REST_INFO
# #ORDER BY FAVORITES
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC