# SELECT ID, IF(LI/TC <= 0.25, 'CRITICAL', IF(LI/TC <= 0.5, 'HIGH', IF(LI/TC <= 0.75, 'MEDIUM', 'LOW'))) AS COLONY_NAME
# FROM 
# (SELECT ID, SIZE_OF_COLONY, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) LI, COUNT(*) OVER() AS TC
# FROM ECOLI_DATA
# ORDER BY SIZE_OF_COLONY DESC) A
# ORDER BY ID

WITH RAN AS (
SELECT ID,RANK() OVER(ORDER BY SIZE_OF_COLONY DESC, ID) R, COUNT(*) OVER() CO
FROM ECOLI_DATA
)

SELECT ED.ID, CASE WHEN CO/4 >= R THEN 'CRITICAL'
         WHEN CO/2 >= R THEN 'HIGH'
         WHEN (CO * 3)/4 >= R THEN 'MEDIUM'
         ELSE 'LOW' END COLONY_NAME
FROM ECOLI_DATA ED JOIN RAN
ON ED.ID = RAN.ID
ORDER BY ID











