WITH FISHES AS (
    SELECT FI.FISH_TYPE,COUNT(ID) FISH_COUNT
FROM FISH_INFO FI JOIN FISH_NAME_INFO FN
ON FI.FISH_TYPE = FN.FISH_TYPE
GROUP BY FI.FISH_TYPE
)

# SELECT *
# FROM FISHES


SELECT FISH_COUNT, FISH_NAME
FROM FISHES LEFT JOIN FISH_NAME_INFO
ON FISHES.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY FISH_COUNT DESC