SELECT PRODUCT_ID, PRODUCT_NAME, TOTAL* PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT FP NATURAL JOIN 
(SELECT ORDER_ID, PRODUCT_ID, SUM(AMOUNT) AS TOTAL
FROM FOOD_ORDER
WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '05' 
GROUP BY PRODUCT_ID) FO
ORDER BY TOTAL_SALES DESC, PRODUCT_ID


# SELECT *
# FROM FOOD_PRODUCT FP JOIN
# (SELECT ORDER_ID, PRODUCT_ID, SUM(AMOUNT) AS TOTAL
# FROM FOOD_ORDER
# WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '05'
# GROUP BY PRODUCT_ID) FO
# ON FP.PRODUCT_ID = FO.PRODUCT_ID
# ORDER BY TOTAL DESC, FP.PRODUCT_ID