SELECT FLAVOR
FROM (
SELECT SHIPMENT_ID, FLAVOR, (TOTAL_ORDER+ ST) AS TOTAL
FROM FIRST_HALF F NATURAL JOIN (select SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) ST
from JULY
GROUP BY FLAVOR) J
ORDER BY TOTAL DESC
LIMIT 3) FF