SELECT EMP_NO, EMP_NAME, GRADE, IF(GRADE= 'S' , SAL*0.2 , IF(GRADE='A', SAL*0.15, IF(GRADE='B', SAL*0.1 , 0))) AS BONUS
FROM(
SELECT HG.EMP_NO, EMP_NAME, SAL, IF(AVG(SCORE) >=96, 'S',  IF(AVG(SCORE)>= 90,'A', IF(AVG(SCORE)>=80, 'B', 'C'))) AS GRADE
FROM HR_GRADE HG JOIN HR_EMPLOYEES HE
ON HG.EMP_NO = HE.EMP_NO
GROUP BY HG.EMP_NO) A
ORDER BY EMP_NO