WITH TIMES AS (
    SELECT ANIMAL_ID, HOUR(DATETIME) HOUR
    FROM ANIMAL_OUTS
)

SELECT HOUR, COUNT(HOUR) COUNT
FROM ANIMAL_OUTS AO JOIN TIMES
ON AO.ANIMAL_ID = TIMES.ANIMAL_ID
WHERE HOUR >= 9 AND HOUR <= 19
GROUP BY HOUR
ORDER BY HOUR

