SELECT MEMBER_NAME, REVIEW_TEXT, LEFT(REVIEW_DATE, 10) AS REVIEW_DATE
FROM MEMBER_PROFILE MP JOIN
(SELECT *
FROM REST_REVIEW RR NATURAL JOIN
(SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY REVIEW_COUNT DESC
LIMIT 1) TEMP) TT
ON MP.MEMBER_ID = TT.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT