WITH PARENTS AS (
    SELECT *
    FROM ITEM_INFO
    WHERE RARITY= "RARE"
)

SELECT ITEM_INFO.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO JOIN
(SELECT ITEM_TREE.ITEM_ID
FROM ITEM_TREE, PARENTS
WHERE PARENTS.ITEM_ID = PARENT_ITEM_ID) A
ON ITEM_INFO.ITEM_ID = A.ITEM_ID
ORDER BY ITEM_INFO.ITEM_ID DESC

