SELECT MONTH(START_DATE) MONTH, C.CAR_ID, COUNT(C.CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C JOIN
(
SELECT CAR_ID, COUNT(CAR_ID) R
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) >=8 AND MONTH(START_DATE) <= 10
GROUP BY CAR_ID
HAVING COUNT(*) >=5
) A
ON C.CAR_ID = A.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH,CAR_ID
ORDER BY MONTH, CAR_ID DESC