WITH CODES AS (
    SELECT(
    SELECT SUM(CODE) FROM SKILLCODES WHERE NAME="Python" OR NAME="C#") AS PYC_CODE
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, CODES
WHERE SKILL_CODE & PYC_CODE != 0
ORDER BY ID