WITH FISHES AS (
    SELECT FISH_TYPE, COUNT(FISH_TYPE) C
    FROM FISH_INFO
    GROUP BY FISH_TYPE    
)


SELECT SUM(C) AS FISH_COUNT
FROM FISHES JOIN FISH_NAME_INFO FN
ON FISHES.FISH_TYPE= FN.FISH_TYPE
WHERE FISH_NAME = "BASS" OR FISH_NAME= "SNAPPER"

# SELECT FI.FISH_TYPE, COUNT(FI.FISH_TYPE), FISH_NAME
# FROM FISH_INFO FI JOIN FISH_NAME_INFO FN
# ON FI.FISH_TYPE= FN.FISH_TYPE
# GROUP BY FI.FISH_TYPE

# SELECT *
# FROM FISH_INFO FI JOIN FISH_NAME_INFO FN
# ON FI.FISH_TYPE= FN.FISH_TYPE
