# SELECT ID, FISH_NAME, LENGTH
# FROM FISH_NAME_INFO FNI JOIN
# (SELECT ID, FI.FISH_TYPE, LENGTH
# FROM FISH_INFO FI JOIN
# (SELECT FISH_TYPE, MAX(LENGTH) MI
# FROM FISH_INFO
# WHERE LENGTH IS NOT NULL
# GROUP BY FISH_TYPE) FI2
# ON FI.FISH_TYPE = FI2.FISH_TYPE
# WHERE LENGTH = MI) FNI2
# ON FNI.FISH_TYPE = FNI2.FISH_TYPE
# ORDER BY ID

WITH BIGFISH AS (
SELECT FISH_TYPE, MAX(LENGTH) LEN
FROM FISH_INFO
GROUP BY FISH_TYPE
)

# WITH ALLFISH AS (
# SELECT *
# FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI
# ON FI.FISH_TYPE = FNI.FISH_TYPE
# )

SELECT ID, FISH_NAME, LENGTH
FROM BIGFISH BF JOIN
(
SELECT ID, FISH_INFO.FISH_TYPE, LENGTH, FISH_NAME
FROM FISH_INFO JOIN FISH_NAME_INFO
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
) AS AF
ON AF.FISH_TYPE= BF.FISH_TYPE
WHERE LENGTH = LEN
ORDER BY ID







