SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO FNI JOIN
(SELECT ID, FI.FISH_TYPE, LENGTH
FROM FISH_INFO FI JOIN
(SELECT FISH_TYPE, MAX(LENGTH) MI
FROM FISH_INFO
WHERE LENGTH IS NOT NULL
GROUP BY FISH_TYPE) FI2
ON FI.FISH_TYPE = FI2.FISH_TYPE
WHERE LENGTH = MI) FNI2
ON FNI.FISH_TYPE = FNI2.FISH_TYPE
ORDER BY ID
