SELECT CATEGORY, SUM(TOTAL_SALES) TOTAL_SALES
FROM BOOK JOIN
(SELECT BOOK_ID, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK_ID) A
ON BOOK.BOOK_ID = A.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY