SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (
SELECT ID, FISH_TYPE, IF(LENGTH IS NULL , 10, LENGTH) AS LENGTH
FROM FISH_INFO) A
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE