WITH CODES AS (SELECT
(SELECT CODE FROM SKILLCODES WHERE NAME='PYTHON') AS PYCODE,
(SELECT CODE FROM SKILLCODES WHERE NAME='C#') AS C_CODE,
(SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY='FRONT END') AS FECODE
FROM DUAL)

SELECT *
FROM
(SELECT IF(SKILL_CODE & FECODE AND SKILL_CODE & PYCODE , "A", 
          IF(SKILL_CODE & C_CODE, "B",IF(SKILL_CODE & FECODE, "C",""))) AS GRADE, ID, EMAIL
FROM DEVELOPERS, CODES
ORDER BY GRADE, ID) A
WHERE GRADE != ""
