WITH PRO AS (
    SELECT TRUNCATE(PRICE/10000, 0) * 10000 AS PRICE_GROUP, TRUNCATE(PRICE/10000, 0) AS P
    FROM PRODUCT
)

SELECT PRICE_GROUP, COUNT(PRICE_GROUP) PRODUCTS
FROM PRO
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP